# Generated by Django 6.0.4 on 2026-06-01 22:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Classe',
            fields=[
                ('idClasse', models.AutoField(primary_key=True, serialize=False)),
                ('nomClasse', models.CharField(max_length=50)),
                ('annee', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='FraisScolaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeFrs', models.CharField(max_length=100)),
                ('montant', models.FloatField()),
                ('classe', models.CharField(blank=True, max_length=50, null=True)),
                ('option', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('idOption', models.AutoField(primary_key=True, serialize=False)),
                ('nomOption', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('idPeriode', models.AutoField(primary_key=True, serialize=False)),
                ('nomPeriode', models.CharField(max_length=50)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('statut', models.CharField(choices=[('VERROUILLE', 'Pas encore ouverte'), ('ACTIVE', "En cours d'encodage"), ('CLOTURE', 'Clôturée (Résultats publiés)')], default='VERROUILLE', max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('idSection', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='SectionCours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(max_length=50)),
                ('maxima', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TypeCours',
            fields=[
                ('idType', models.AutoField(primary_key=True, serialize=False)),
                ('libelle', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('idUser', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Eleve',
            fields=[
                ('matriculeEleve', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('postnom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('sexe', models.CharField(max_length=10)),
                ('date_naissance', models.DateField()),
                ('lieu_naissance', models.CharField(max_length=100)),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.classe')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('idEns', models.AutoField(primary_key=True, serialize=False)),
                ('matriculeEns', models.CharField(max_length=50, unique=True, verbose_name='Matricule Enseignant')),
                ('nom', models.CharField(max_length=50)),
                ('postnom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('grade', models.CharField(max_length=50)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='enseignant_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cours',
            fields=[
                ('idCours', models.AutoField(primary_key=True, serialize=False)),
                ('code_cours', models.CharField(max_length=20)),
                ('libelle', models.CharField(max_length=150)),
                ('ponderation', models.FloatField()),
                ('classes', models.ManyToManyField(help_text='Sélectionnez la ou les classes spécifiques qui suivent ce cours.', related_name='cours_etudies', to='management.classe')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.enseignant', verbose_name='Enseignant Attribué')),
                ('section_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.sectioncours')),
                ('type_cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.typecours')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='idEns',
            field=models.ForeignKey(blank=True, db_column='idEns', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classe_titulaire', to='management.enseignant'),
        ),
        migrations.CreateModel(
            name='CentralisationClasse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_soumission', models.DateTimeField(auto_now_add=True, verbose_name='Date de soumission')),
                ('est_valide', models.BooleanField(default=False, verbose_name='Validé par le Proviseur')),
                ('classe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.classe', verbose_name='Classe concernée')),
                ('titulaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.enseignant', verbose_name='Titulaire')),
            ],
        ),
        migrations.AddField(
            model_name='classe',
            name='option',
            field=models.ForeignKey(db_column='idOption', on_delete=django.db.models.deletion.CASCADE, to='management.option'),
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numRecur', models.CharField(max_length=50)),
                ('montant', models.FloatField()),
                ('date', models.DateField(auto_now_add=True)),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='management.eleve')),
                ('frais_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.fraisscolaire')),
            ],
        ),
        migrations.AddField(
            model_name='option',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.section'),
        ),
        migrations.CreateModel(
            name='Cotes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.FloatField(blank=True, null=True)),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotes_cours', to='management.cours')),
                ('eleve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotes', to='management.eleve')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cotes_periode', to='management.periode')),
            ],
            options={
                'unique_together': {('eleve', 'cours', 'periode')},
            },
        ),
    ]
