# Generated by Django 6.0.4 on 2026-06-01 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sectioncours',
            name='nom_section',
        ),
        migrations.AlterField(
            model_name='sectioncours',
            name='maxima',
            field=models.FloatField(unique=True),
        ),
    ]
