# Generated by Django 6.0.4 on 2026-06-01 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_remove_sectioncours_nom_section_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cours',
            old_name='section_cours',
            new_name='max',
        ),
    ]
