# Generated by Django 6.0.4 on 2026-06-02 02:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_rename_section_cours_cours_max'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.classe')),
                ('cours', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.cours')),
                ('enseignant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='management.enseignant')),
            ],
            options={
                'unique_together': {('cours', 'classe')},
            },
        ),
    ]
