# Generated by Django 6.0.4 on 2026-06-02 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_attribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='classe',
            name='type_bulletin',
            field=models.CharField(choices=[('co', "Cycle d'Orientation"), ('sci', 'Scientifique'), ('elec', 'Electricité'), ('peda', 'Pédagogie'), ('cg', 'Commerciale & Gestion')], default='co', max_length=10),
        ),
    ]
