# Generated by Django 6.0.4 on 2026-06-02 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_classe_type_bulletin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
