# Generated by Django 6.0.4 on 2026-06-02 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_domaine_cours_domaine'),
    ]

    operations = [
        migrations.AddField(
            model_name='attribution',
            name='max_examen',
            field=models.FloatField(default=40, verbose_name='Max Examen'),
        ),
        migrations.AddField(
            model_name='attribution',
            name='max_tj',
            field=models.FloatField(default=20, verbose_name='Max Travaux Journaliers'),
        ),
    ]
