# Generated by Django 6.0.4 on 2026-06-10 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_centralisationclasse_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='telephone',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
