# Generated by Django 6.0.4 on 2026-06-15 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_enseignant_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationresultats',
            name='classe',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='management.classe'),
        ),
        migrations.AddField(
            model_name='publicationresultats',
            name='periode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='management.periode'),
        ),
        migrations.AlterField(
            model_name='publicationresultats',
            name='est_publiee',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='publicationresultats',
            unique_together={('classe', 'periode')},
        ),
    ]
