# Generated by Django 6.0.4 on 2026-06-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_publicationresultats_classe_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='telephone_parent',
            field=models.CharField(blank=True, help_text='Format: +243XXXXXXXXX', max_length=20, null=True),
        ),
    ]
