# Generated by Django 6.0.4 on 2026-07-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_eleve_telephone_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='adresseMail',
            field=models.CharField(blank=True, help_text='Format: xxxx@gmail.com', max_length=20, null=True),
        ),
    ]
