# Generated by Django 6.0.4 on 2026-07-03 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_eleve_adressemail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleve',
            name='adresseMail',
            field=models.CharField(blank=True, help_text='Format: xxxx@gmail.com', max_length=254, null=True),
        ),
    ]
