# Generated by Django 6.0.4 on 2026-07-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0015_alter_eleve_adressemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='Annonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200, verbose_name="Titre de l'annonce")),
                ('contenu', models.TextField(verbose_name='Contenu / Message')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='annonces/', verbose_name="Photo d'illustration")),
                ('date_publication', models.DateTimeField(auto_now_add=True, verbose_name='Date de publication')),
                ('est_active', models.BooleanField(default=True, verbose_name='Afficher sur le site')),
            ],
            options={
                'verbose_name': 'Annonce',
                'verbose_name_plural': 'Anonces',
                'ordering': ['-date_publication'],
            },
        ),
    ]
