"""
Django settings for vungi_portal project.

Generated by 'django-admin startproject' using Django 6.0.4.
Optimized for deployment on PythonAnywhere with SQLite.
"""

import os
from pathlib import Path
import mimetypes

# Correction des types MIME pour Windows
mimetypes.add_type("text/css", ".css", True)
mimetypes.add_type("text/javascript", ".js", True)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-dev-key-portail-vungi')

# CORRECTION SÉCURISÉE DU DEBUG : En local sur ton PC, il sera à True. 
# En ligne sur PythonAnywhere, il te suffira de créer une variable d'environnement DJANGO_DEBUG='False'
DEBUG = os.getenv('DJANGO_DEBUG', 'True').lower() in ('1', 'true', 'yes', 'on')

# Hôtes autorisés
ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    'kakulejonathan.pythonanywhere.com',
]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'management',  # Ton application principale
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'vungi_portal.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'], # Recommandé si tu as un dossier templates global
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'vungi_portal.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Lubumbashi'

USE_I18N = True

USE_TZ = True


# =========================================================================
# CONFIGURATION DES FICHIERS STATIQUES CORRIGÉE POUR LE DESIGN DE L'ADMIN
# =========================================================================

STATIC_URL = '/static/'

# Dossier où Django va chercher tes fichiers statiques personnalisés en local
STATICFILES_DIRS = [
    BASE_DIR / 'staticfiles',
]

# Dossier final utilisé par PythonAnywhere lors du collectstatic
STATIC_ROOT = BASE_DIR / 'production_staticfiles'


# Redirection d'authentification
LOGOUT_REDIRECT_URL = 'home'
LOGIN_URL = 'home'
LOGIN_REDIRECT_URL = 'home'# =========================================================================
# CONFIGURATION DE L'ENVOI D'E-MAILS (SMTP GMAIL)
# =========================================================================
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True

# Remplace par l'adresse Gmail officielle de l'Institut Vungi
EMAIL_HOST_USER = 'institutvungi@gmail.com'  

# REMPLACE PAR TON MOT DE PASSE D'APPLICATION DE 16 CARACTÈRES (Pas ton mot de passe normal)
EMAIL_HOST_PASSWORD = os.getenv('DJANGO_EMAIL_PASSWORD', 'ptowkvqpjyjqumcv')  

# Nom qui s'affichera dans la boîte mail du parent
DEFAULT_FROM_EMAIL = f"Institut Vungi <{EMAIL_HOST_USER}>"

SITE_URL = 'https://kakulejonathan.pythonanywhere.com'

# Configuration des fichiers médias (images des annonces, etc.)
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')